### ISSUE TITLE
12c - declarative component variable problem

### ISSUE THREAD

**Issue by ayhangungor** [oracle/apps-cloud-ui-kit#1]
in the following file, ```componentVar``` should be different from ```component```. this crashes some pages to load.

```
UIKitCommon/public_html/oracle/apps/uikit/common/declarativeComponents/PageHeaderDC.jspx

line 13 : <af:componentDef var="attrs" componentVar="component">
```

**Comment by lancysilveira** [comment]
Issue was re-produceable on 12c but not 11g.
PageHeaderDC.jspx fixed to change componentVar from 'component' to 'comp'.
Fixed and tested on 11g and 12c.
