### ISSUE TITLE
How to change the theme in RDK application

### ISSUE THREAD

**Issue by nnurmano** [oracle/apps-cloud-ui-kit#5]
I would like to change the theme from default SkyBlue to e.g. AutumnRed, how to do so?

**Comment by lancysilveira** [comment]
In the trinidad-config.xml file in DemoMaster.jpr, you will see the skin family set using EL as follows:
<skin-family>#{SessionState.skinFamily}</skin-family>

The default value for variable _skinFamily has been set to 'SkyBlueTheme' in the file SessionState.java in DemoData.jpr. To change the default skin at design time, you need to set this variable to the desired skin family name. 

The available skin family names can be found in the trinidad-skins.xml file in DemoMaster.jpr. For example the Autumn Red theme is called AutumRedTheme.

Changing the skin at runtime involves programmatically changing the value of variable SessionState.skinFamily used in the EL above. This has been demonstrated in the Appearance feature in the RDK.
