### ISSUE TITLE
Horizontal scrollbar with Contacts list

### ISSUE THREAD

**Issue by nnurmano** [oracle/apps-cloud-ui-kit#6]
When running RDK on JDeveloper 12.2.1.3, I see horizontal scrollbar in the Contact list, how to avoid such a behavior?

![image](https://user-images.githubusercontent.com/3382143/34809948-951071a0-f6c2-11e7-93d9-88c713523b24.png)

**Comment by lancysilveira** [comment]
Dear nomadus, the sample card content has been developed on 11.1.1.9.0 and checked with Chrome on OSX. We have not styled the sample application for all combinations of browsers, operating systems and platforms. 

While the sample application will not error on other browsers, platforms, and versions of ADF like 12c, it is expected that there will be some minor styling adjustments for your chosen development and deployment environment. Besides, RDK consumers will be developing their own card content. 

Hence closing this issue without any code change.
